### ISSUE TITLE
GroupSlice: Wrong order of result

### ISSUE THREAD

**Issue by g4s8** [artipie/http#203]
GroupSlice may fail with error:
```
artipie         | [INFO] 2020-07-20 13:04:16,093 HttpClient@19dbfba7-26 com.artipie.http.DockerRoutingSlice - Failure: java.util.concurrent.CompletionException: java.lang.IllegalStateException: Wrong order of result
artipie         | 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
artipie         | 	at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:46)
artipie         | 	at io.reactivex.internal.operators.maybe.MaybeSwitchIfEmptySingle$SwitchIfEmptyMaybeObserver$OtherSingleObserver.onError(MaybeSwitchIfEmptySingle.java:122)
artipie         | 	at io.reactivex.internal.operators.single.SingleDelayWithCompletable$OtherObserver.onError(SingleDelayWithCompletable.java:64)
artipie         | 	at io.reactivex.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onError(SingleFlatMapCompletable.java:97)
artipie         | 	at io.reactivex.subjects.SingleSubject.onError(SingleSubject.java:153)
artipie         | 	at hu.akarnokd.rxjava2.interop.SingleInterop.lambda$fromFuture$2(SingleInterop.java:79)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
artipie         | 	at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:46)
artipie         | 	at io.reactivex.internal.operators.flowable.FlowableSingleSingle$SingleElementSubscriber.onError(FlowableSingleSingle.java:97)
artipie         | 	at org.eclipse.jetty.reactive.client.internal.AbstractSingleProcessor.onError(AbstractSingleProcessor.java:119)
artipie         | 	at io.reactivex.internal.util.HalfSerializer.onError(HalfSerializer.java:70)
artipie         | 	at io.reactivex.internal.subscribers.StrictSubscriber.onError(StrictSubscriber.java:103)
artipie         | 	at io.reactivex.internal.operators.single.SingleToFlowable$SingleToFlowableObserver.onError(SingleToFlowable.java:67)
artipie         | 	at io.reactivex.internal.disposables.EmptyDisposable.error(EmptyDisposable.java:78)
artipie         | 	at io.reactivex.internal.operators.single.SingleError.subscribeActual(SingleError.java:42)
artipie         | 	at io.reactivex.Single.subscribe(Single.java:3603)
artipie         | 	at io.reactivex.internal.operators.single.SingleToFlowable.subscribeActual(SingleToFlowable.java:37)
artipie         | 	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
artipie         | 	at io.reactivex.Flowable.subscribe(Flowable.java:14868)
artipie         | 	at org.eclipse.jetty.reactive.client.internal.ResponseListenerProcessor.onHeaders(ResponseListenerProcessor.java:91)
artipie         | 	at org.eclipse.jetty.client.ResponseNotifier.notifyHeaders(ResponseNotifier.java:100)
artipie         | 	at org.eclipse.jetty.client.ResponseNotifier.notifyHeaders(ResponseNotifier.java:92)
artipie         | 	at org.eclipse.jetty.client.HttpReceiver.responseHeaders(HttpReceiver.java:322)
artipie         | 	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.headerComplete(HttpReceiverOverHTTP.java:284)
artipie         | 	at org.eclipse.jetty.http.HttpParser.parseFields(HttpParser.java:1220)
artipie         | 	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1503)
artipie         | 	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:200)
artipie         | 	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:141)
artipie         | 	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:75)
artipie         | 	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:133)
artipie         | 	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:156)
artipie         | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
artipie         | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
artipie         | 	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:543)
artipie         | 	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:398)
artipie         | 	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:161)
artipie         | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
artipie         | 	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
artipie         | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
artipie         | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
artipie         | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
artipie         | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
artipie         | 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
artipie         | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
artipie         | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
artipie         | 	at java.base/java.lang.Thread.run(Unknown Source)
artipie         | Caused by: java.lang.IllegalStateException: Wrong order of result
artipie         | 	at com.artipie.http.group.GroupResults.complete(GroupResults.java:89)
artipie         | 	at com.artipie.http.group.GroupConnection.accept(GroupConnection.java:71)
artipie         | 	at com.artipie.http.rs.RsWithStatus$ConWithStatus.accept(RsWithStatus.java:109)
artipie         | 	at com.artipie.http.rs.StandardRs.lambda$static$0(StandardRs.java:41)
artipie         | 	at com.artipie.http.rs.StandardRs.send(StandardRs.java:76)
artipie         | 	at com.artipie.http.rs.RsWithStatus.send(RsWithStatus.java:70)
artipie         | 	at com.artipie.http.rs.StandardRs.send(StandardRs.java:76)
artipie         | 	at com.artipie.http.async.AsyncResponse.lambda$send$0(AsyncResponse.java:61)
artipie         | 	... 52 more
```

**Comment by g4s8** [comment]
@rultor release, tag=`0.15.1`

**Comment by g4s8** [comment]
@rultor release, tag=`0.15.2`

**Comment by g4s8** [comment]
Done

**Comment by 0crat** [comment]
Job was finished in 47 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
